Changing coverage check to be defined as a percentage

diff --git a/.yamato/yamato-config.yml b/.yamato/yamato-config.yml
--- a/.yamato/yamato-config.yml
+++ b/.yamato/yamato-config.yml
@@ -1,11 +1,11 @@
 name: Endpoint Unit Tests
 agent:
     type: Unity::VM
-    image: robotics/ci-ubuntu20:v0.1.0-795910
+    image: robotics/ci-ros2-galactic-ubuntu20:v0.0.2-916903
     flavor: i1.large
 variables:
-  # Coverage measured as a ratio (out of 1.0)
-  COVERAGE_EXPECTED: 0.3
+  # Coverage measured as a percentage (out of 100)
+  COVERAGE_EXPECTED: 30
 commands:
     # run unit tests and save test results in /home/bokken/build/output/Unity-Technologies/ROS-TCP-Endpoint
     - command: |
@@ -18,8 +18,8 @@ commands:
     - command: |
         linecoverage=$(head -2 test-results/coverage.xml | grep -Eo 'line-rate="[0-9]+([.][0-9]+)?"' | grep -Eo "[0-9]+([.][0-9]+)?")
         echo "Line coverage: $linecoverage"
-        if (( $(echo "$linecoverage < $COVERAGE_EXPECTED" | bc -l) ));
-        then echo "ERROR: Code Coverage is under threshold of $COVERAGE_EXPECTED" && exit 1
+        if (( $(echo "$linecoverage * 100.0 < $COVERAGE_EXPECTED" | bc -l) ));
+        then echo "ERROR: Code Coverage is under threshold of $COVERAGE_EXPECTED%" && exit 1
         fi
 triggers:
     cancel_old_ci: true
